### ISSUE TITLE
Dots or no dots

### ISSUE THREAD

**Issue by art0007i** [zkxs/neos-mod-list#11]
Currently some of the mod descriptions have dots at the end and some don't, I think we should keep them consistent but do we remove all the dots or add them where there aren't any

**Comment by zkxs** [comment]
My vote is for no dots. Currently each line is just a simple single-sentence (or even sentence fragment) description of what the mod does, so there's no need for using periods to delimit sentences. In the future we might want to have multiple sentences in a description for a mod at which point using periods would make more sense, but I prefer we avoid that and let users click on a mod link if they want more detail.

**Comment by EIA485** [comment]
i agree, remove all the dots
