### ISSUE TITLE
Cheese4All has weird visuals verses the real Cheese

### ISSUE THREAD

**Issue by AshtonSparx** [zkxs/neos-mod-list#12]
![image](https://user-images.githubusercontent.com/53165730/140605897-45c7465d-6db8-443a-b1f5-0e26099daf0d.png)

The cheese curser looks fine on Prime's videos. But mine has a weird line on the tip.

![image](https://user-images.githubusercontent.com/53165730/140605912-9d25519c-a93a-496b-8d60-995078d15531.png)

**Comment by EIA485** [comment]
please go ahead and open a issue on the mod's repo
